### ISSUE TITLE
Test recipes and repair any that are failing

### ISSUE THREAD

**Issue by headmetal** [ACCESS-NRI/CMIP7-Hackathon#10]

**Comment by headmetal** [comment]
Failing recipes:

- [x] `general/recipe_climwip_test_performance_sigma.yml` - *FileNotFoundError: Failed to search ESGF, unable to connect:* Data issue. Is currently trying to search ESGF via HTTPS request.
- [ ]  `general/recipe_monitor.yml` - *FileNotFoundError: Failed to search ESGF, unable to connect:* Data issue. Is currently trying to search ESGF via HTTPS request.
- [X] `ocean/maps/recipe_ocean_quadmap.yml` - *FileNotFoundError: Failed to search ESGF, unable to connect:* Data issue. Is currently trying to search ESGF via HTTPS request.
- [ ] `sea-ice/recipe_seaice.yml` - *raise DiagnosticError(f"{err_msg}: file does not exist.") esmvalcore._task.DiagnosticError: Cannot execute script '/home/189/fc6164/esmValTool/CMIP7-Hackathon/recipes/sea-ice/seaice_graphs.py'*. <<- @flicj191 Can you please take a look at this one when you get a moment? I can see this path in the *.yml file - I'm guessing its a permissions problem as its in your home directory maybe?
- [ ] `ocean/transects/transect2.yml` - *ValueError: extract_transect: Not implemented for irregular arrays!
Try regridding the data first* Gridding issue.
- [ ] `ocean/transects/transect3.yml` - *ValueError: extract_transect: Not implemented for irregular arrays!
Try regridding the data first* Gridding issue.
- [ ] `ocean/transects/transects_all.yml` - *ValueError: extract_transect: Not implemented for irregular arrays!
Try regridding the data first* Gridding issue.

**Comment by rbeucher** [comment]
Thanks. Make sure search_esgf is set to "never" in your configuration.

**Comment by flicj191** [comment]
The script is in the repo, if there's a way to update the path in the recipe when the repo is cloned? but it seems just like editing the path manually?

**Comment by rbeucher** [comment]
There are workarounds, we could force the update of the path. Pb it is not portable.

**Comment by rbeucher** [comment]
I am fixing the https request ones

**Comment by rbeucher** [comment]
https://github.com/ESMValGroup/ESMValCore/issues/2328

**Comment by rbeucher** [comment]
the native6 folder in xp65 was missing ERA5 data. I am syncing it. It will take a bit of time...

**Comment by rbeucher** [comment]
- [X] recipe_climwip_test_performance_sigma
- [ ] recipe monitor is trying to download some naturalearth data. https://naturalearth.s3.amazonaws.com/50m_physical/ne_50m_coastline.zip
We have that already in `/g/data/xp65/public/apps/cartopy-data`. I wonder where it expects the data to be...
- [X] `ocean/maps/recipe_ocean_quadmap.yml` - *FileNotFoundError: Failed to search ESGF, unable to connect:* Data issue. Is currently trying to search ESGF via HTTPS request. -->ct11 was not mounted....
- [X] ocean/transects/transect3.yml - ValueError: extract_transect: Not implemented for irregular arrays!
Try regridding the data first Gridding issue. --> works with the regriding but takes too long

**Comment by flicj191** [comment]
i put something like this in my pbs job :
`export CARTOPY_DATA_DIR=/g/data/xp65/public/apps/cartopy-data`
not sure if there's a better way, that's in `cartopy` when it needs data to map

**Comment by rbeucher** [comment]
> i put something like this in my pbs job :
export CARTOPY_DATA_DIR=/g/data/xp65/public/apps/cartopy-data
not sure if there's a better way, that's in cartopy when it needs data to map

This should be picked up by the `auxiliary_data_dir` option in the config file... currently set to `/g/data/xp65/public/apps/cartopy-data`

**Comment by flicj191** [comment]
yeah, not sure, that didn't work for me sometimes, i can check it again, that was a while ago

**Comment by rbeucher** [comment]
For the recipe_monitor, the diagnostic can take a `cartopy_data_dir` option... This should work but gosh this is ugly...

**Comment by flicj191** [comment]
> For the recipe_monitor, the diagnostic can take an `cartopy_data_dir` option... This should work but gosh this is ugly...

yea i just saw that too

**Comment by rbeucher** [comment]
@headmetal the regrid preprocessor works for transect3 and should also work for transect2... But it is too long...(57 min)
