### ISSUE TITLE
Skeleton recipe + python script diagnostic

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-NRI/CMIP7-Hackathon#13]
Hi @flicj191 ,

As discussed this morning, it would be great to have a skeleton recipe + script that illustrate how to make a diagnostic.
I have already made a video about that but we don't have a skeleton.

R

**Comment by flicj191** [comment]
added to sample_recipe folder. made to run successfully and plot something but doesn't do anything useful

**Comment by rbeucher** [comment]
Looks good. Thanks @flicj191
