### ISSUE TITLE
How to use observational dataset in a recipe?

### ISSUE THREAD

**Issue by yyplanton** [ACCESS-NRI/CMIP7-Hackathon#24]
I am trying to create a metric using 'ts'.
According to the list of available observations I should be able to use HadISST or CFSR or others.
If I call any observational  dataset I obtain the exact same error: KeyError: 'diagnostic' (see attachment).
I assume that ESMValTool cannot find the asked variable. But I am nut sure what is the error.
Note that the recipe runs if I remove observational datasets.
[main_log_debug.txt](https://github.com/ACCESS-NRI/CMIP7-Hackathon/files/14531552/main_log_debug.txt)
[recipe_enso_amplitude.txt](https://github.com/ACCESS-NRI/CMIP7-Hackathon/files/14531571/recipe_enso_amplitude.txt)

**Comment by headmetal** [comment]
We do have a simple ESMValTool ENSO example [here](https://github.com/ACCESS-NRI/CMIP7-Hackathon/tree/main/recipes/enso) that uses HadISST that might be helpful?

In this recipe ([enso_analysis.yml](https://github.com/ACCESS-NRI/CMIP7-Hackathon/blob/main/recipes/enso/enso_analysis.yml)) we identify and load the OBS data under `diagnostics>variables` and `diagnostics>additional_datasets` and not under `datasets` as in your script above.

**Comment by yyplanton** [comment]
Thank you. I made some minor changes an now my code runs.

**Comment by headmetal** [comment]
Great, no problems.
