### ISSUE TITLE
check_hackathon can't find recipes/sea-ice/recipe_seaice.yml

### ISSUE THREAD

**Issue by aekiss** [ACCESS-NRI/CMIP7-Hackathon#25]
`check_hackathon` tells me
```
sed: can't read /scratch/nf33/aek156/CMIP7-Hackathon/recipes/sea-ice/recipe_seaice.yml: No such file or directory
```
I guess that should be `/scratch/nf33/aek156/CMIP7-Hackathon/recipes/sea-ice/recipe_seaice_extents_sh.yml`?

**Comment by flicj191** [comment]
Yes! it should be, apologies, it didn't update through to the checks, I changed the name of the recipe as there was a recipe_seaice already in the ESMValTool collection of available recipes..
that recipe can be run with 
`run_recipe recipes/sea-ice/recipe_seaice_extents_sh.yml` 
from the CMIP7-Hackathon folder after the checks.

**Comment by rbeucher** [comment]
Fixed
