### ISSUE TITLE
Sea-ice recipes

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-NRI/CMIP7-Hackathon#4]
@flicj191 if you could add a version of the sea-ice recipe here, that would be awesome.

Now what we need for the workshop:

Make it work for ACCESS-ESM1-5 CMIP6 outputs.

If the recipe uses model means, we also need a couple more models from the replicas on gadi. UKESM, CESM?

The idea is to have recipes that take less than 5 mins to run.

Strategies for that include:

reduced time range
reduced number of datasets
reduced number of diagnostics
change resolution of the grid
I think it would also be a good idea to document the recipes with comments, to make it very clear what each sections are about....

**Comment by flicj191** [comment]
-  [x] update diagnostic to plot multiple models in minima and maxima trends
-  [ ] check references
